# Production environment overrides
environment: production

# Full production resources
postgresql:
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  persistence:
    enabled: true
    size: 5Gi

kafka:
  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 1Gi
      cpu: 500m
  persistence:
    enabled: true
    size: 10Gi

quarkus:
  resources:
    limits:
      memory: 2Gi
      cpu: 1000m
    requests:
      memory: 1Gi
      cpu: 500m
  debug:
    enabled: false

# Disable debug features in production
devSpaces:
  workspace:
    variables:
      ENABLE_DEBUG_PORTS: "false"
      POSTGRES_EXPOSE_PORT: "false"

# Full monitoring stack
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s

# Enable autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Production route
route:
  host: ddd-workshop.apps.cluster.example.com

# Full security enforcement
podSecurityContext:
  enabled: true

securityContext:
  enabled: true
  readOnlyRootFilesystem: true

# Strict network policies
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: openshift-devspaces
    - from:
        - namespaceSelector:
            matchLabels:
              name: ddd-workshop-prod
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: ddd-workshop-prod

# Production resource quotas
resourceQuota:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
