{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ddd-workshop.fullname" . }}-network-policy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ddd-workshop.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ddd-workshop.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "ddd-workshop.selectorLabels" . | nindent 14 }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.global.namespace }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "ddd-workshop.selectorLabels" . | nindent 14 }}
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
  {{- end }}
---
{{- end }}
