{{- if .Values.quarkus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddd-workshop.fullname" . }}-quarkus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ddd-workshop.labels" . | nindent 4 }}
    component: quarkus
spec:
  type: {{ .Values.quarkus.service.type }}
  ports:
    - port: {{ .Values.quarkus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.quarkus.debug.enabled }}
    - port: {{ .Values.quarkus.debug.port }}
      targetPort: debug
      protocol: TCP
      name: debug
    {{- end }}
  selector:
    {{- include "ddd-workshop.selectorLabels" . | nindent 4 }}
    component: quarkus
---
{{- end }}
